name: scribase-mail-dev

services:
  postgres:
    image: postgres:16
    container_name: scribase-mail-db-dev
    restart: always
    environment:
      - POSTGRES_USER=usesend
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=usesend
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "54320:5432"

  redis:
    image: redis:7
    container_name: scribase-mail-redis-dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command: ["redis-server", "--maxmemory-policy", "noeviction"]

volumes:
  database:
  redis:
