/**
 * Store raw .eml files and attachment blobs.
 *
 * Priority:
 *  1. OCI Object Storage when OCI_STORAGE_NAMESPACE + OCI_STORAGE_BUCKET are set.
 *  2. Local disk at INBOUND_STORAGE_DIR (default: /tmp/scribase-inbound) for dev.
 *
 * Both paths return a `storageKey` string that is saved in the database.
 * Signed download URLs are generated by the web app (apps/web).
 */

import { readFileSync, mkdirSync, writeFileSync } from "fs";
import path from "path";

// Lazily import OCI SDK only when env vars are present to keep cold starts fast
// in environments without OCI credentials.
type OciClientLike = {
  putObject(req: {
    namespaceName: string;
    bucketName: string;
    putObjectBody: Buffer;
    objectName: string;
    contentLength: number;
    contentType?: string;
  }): Promise<void>;
};

type OciAuthProvider = {
  new (config: object): OciAuthProvider;
};

const OCI_NAMESPACE = process.env.OCI_STORAGE_NAMESPACE ?? "";
const OCI_BUCKET = process.env.OCI_STORAGE_BUCKET ?? "";
const LOCAL_DIR =
  process.env.INBOUND_STORAGE_DIR ?? "/tmp/scribase-inbound";

function isOciConfigured(): boolean {
  return Boolean(
    OCI_NAMESPACE &&
    OCI_BUCKET &&
    (process.env.OCI_PRIVATE_KEY || process.env.OCI_PRIVATE_KEY_PATH),
  );
}

async function getOciClient(): Promise<OciClientLike | null> {
  if (!isOciConfigured()) return null;
  try {
    // Dynamic import to avoid loading 3 MB of OCI SDK unless configured.
    const { ObjectStorageClient } = await import("oci-objectstorage") as {
      ObjectStorageClient: new (cfg: object) => OciClientLike;
    };
    const { SimpleAuthenticationDetailsProvider } = await import(
      "oci-common"
    ) as {
      SimpleAuthenticationDetailsProvider: OciAuthProvider;
    };

    const privateKeyContent = process.env.OCI_PRIVATE_KEY
      ? Buffer.from(process.env.OCI_PRIVATE_KEY, "utf-8")
      : process.env.OCI_PRIVATE_KEY_PATH
        ? readFileSync(process.env.OCI_PRIVATE_KEY_PATH)
        : null;

    if (!privateKeyContent) return null;

    const provider = new (SimpleAuthenticationDetailsProvider as unknown as new (
      tenancy: string,
      user: string,
      fingerprint: string,
      privateKey: string,
      passphrase: string | null,
      region: string,
    ) => object)(
      process.env.OCI_TENANCY ?? "",
      process.env.OCI_USER ?? "",
      process.env.OCI_FINGERPRINT ?? "",
      privateKeyContent.toString("utf-8"),
      process.env.OCI_PRIVATE_KEY_PASSPHRASE ?? null,
      process.env.OCI_REGION ?? "eu-frankfurt-1",
    );

    const client = new ObjectStorageClient({ authenticationDetailsProvider: provider });
    return client as unknown as OciClientLike;
  } catch {
    return null;
  }
}

/** Upload a buffer and return the object key. */
export async function storeObject(
  key: string,
  data: Buffer,
  contentType = "application/octet-stream",
): Promise<string> {
  const ociClient = await getOciClient();

  if (ociClient) {
    await ociClient.putObject({
      namespaceName: OCI_NAMESPACE,
      bucketName: OCI_BUCKET,
      objectName: key,
      putObjectBody: data,
      contentLength: data.length,
      contentType,
    });
    return key;
  }

  // Fallback: local disk
  const fullPath = path.join(LOCAL_DIR, key);
  mkdirSync(path.dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, data);
  return key;
}
