/**
 * Store raw .eml files and attachment blobs.
 *
 * Priority:
 *  1. OCI Object Storage when OCI_STORAGE_NAMESPACE + OCI_STORAGE_BUCKET are set.
 *  2. Local disk at INBOUND_STORAGE_DIR (default: /tmp/scribase-inbound) for dev.
 *
 * Both paths return a `storageKey` string that is saved in the database.
 * Signed download URLs are generated by the web app (apps/web).
 */

import { readFileSync, mkdirSync, writeFileSync } from "fs";
import path from "path";

type OciObjectStorageClient = import("oci-objectstorage").ObjectStorageClient;

const OCI_NAMESPACE = process.env.OCI_STORAGE_NAMESPACE ?? "";
const OCI_BUCKET = process.env.OCI_STORAGE_BUCKET ?? "";
const LOCAL_DIR =
  process.env.INBOUND_STORAGE_DIR ?? "/tmp/scribase-inbound";

function isOciConfigured(): boolean {
  return Boolean(
    OCI_NAMESPACE &&
    OCI_BUCKET &&
    (process.env.OCI_PRIVATE_KEY || process.env.OCI_PRIVATE_KEY_PATH),
  );
}

let clientPromise: Promise<OciObjectStorageClient | null> | null = null;

// The OCI SDK is imported lazily so dev setups without credentials stay light.
// Once OCI is configured, errors surface instead of silently writing to disk.
async function createOciClient(): Promise<OciObjectStorageClient | null> {
  if (!isOciConfigured()) return null;

  const [{ ObjectStorageClient }, common] = await Promise.all([
    import("oci-objectstorage"),
    import("oci-common"),
  ]);
  const privateKey = process.env.OCI_PRIVATE_KEY
    ? process.env.OCI_PRIVATE_KEY
    : readFileSync(process.env.OCI_PRIVATE_KEY_PATH as string, "utf-8");

  const provider = new common.SimpleAuthenticationDetailsProvider(
    process.env.OCI_TENANCY ?? "",
    process.env.OCI_USER ?? "",
    process.env.OCI_FINGERPRINT ?? "",
    privateKey,
    process.env.OCI_PRIVATE_KEY_PASSPHRASE ?? null,
    common.Region.fromRegionId(process.env.OCI_REGION ?? "eu-frankfurt-1"),
  );
  return new ObjectStorageClient({ authenticationDetailsProvider: provider });
}

function getOciClient(): Promise<OciObjectStorageClient | null> {
  clientPromise ??= createOciClient().catch((error: unknown) => {
    clientPromise = null; // retry on the next message
    throw error;
  });
  return clientPromise;
}

/** Upload a buffer and return the object key. */
export async function storeObject(
  key: string,
  data: Buffer,
  contentType = "application/octet-stream",
): Promise<string> {
  const ociClient = await getOciClient();

  if (ociClient) {
    // Throws on failure, so the MX answers 4xx and the sender retries.
    await ociClient.putObject({
      namespaceName: OCI_NAMESPACE,
      bucketName: OCI_BUCKET,
      objectName: key,
      putObjectBody: data,
      contentLength: data.length,
      contentType,
    });
    return key;
  }

  // Fallback: local disk
  const fullPath = path.join(LOCAL_DIR, key);
  mkdirSync(path.dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, data);
  return key;
}
